pidev/src/pidev/UserBundle/Entity/Annonces.php
<?php

namespace pidev\UserBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
/**
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="pidev\UserBundle\Entity\AnnoncesRepository")
 */
class Annonces
{

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="date", type="date")
     */
    protected $date;

    /**
     * @ORM\Column(name="TITRE", type="string", length=255)
     */
    protected $TITRE;
    /**
     * @ORM\Column(name="NOMBRE_DE_CYLINDRES", type="integer")
     */
    protected $NOMBRE_DE_CYLINDRES;
    /**
     * @ORM\Column(name="ENERGIE", type="string", length=255)
     */
    protected $ENERGIE;
    /**
     * @ORM\Column(name="PUISSANCE_FISCALE", type="string", length=255)
     */
    protected $PUISSANCE_FISCALE;
    /**
     * @ORM\Column(name="CYLINDREE", type="float")
     */
    protected $CYLINDREE;
    /**
     * @ORM\Column(name="BOITE", type="string", length=255)
     */
    protected $BOITE;


    /**
     * @ORM\Column(name="DESCRIPITION", type="text")
     */
    protected $DESCRIPITION;

    /**
     * @ORM\Column(name="VALIDATION", type="boolean")
     */
    private $VALIDATION = true;
    /**
     * @ORM\Column(name="PRIX", type="float")
     */
    protected $PRIX;
    /**
     * @ORM\Column(name="region", type="string")
     */
    protected $region;


    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @JoinColumn(name="user",referencedColumnName="id")
     */
    protected $user;

    /**
     * @return mixed
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * @param mixed $region
     */
    public function setRegion($region)
    {
        $this->region = $region;
    }


    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * @ORM\Column(name="image", type="string" ,nullable=true )
     */
    protected $image;
    /**
     * @ORM\Column(name="image1", type="string" ,nullable=true )
     */
    protected $image1;
    /**
     * @ORM\Column(name="image2", type="string" ,nullable=true )
     */
    protected $image2;
    /**
     * @ORM\Column(name="image3", type="string" ,nullable=true )
     */
    protected $image3;


    /**
     * @return mixed
     */
    public function getImage1()
    {
        return $this->image1;
    }

    /**
     * @param mixed $image1
     */
    public function setImage1($image1)
    {
        $this->image1 = $image1;
    }

    /**
     * @return mixed
     */
    public function getImage2()
    {
        return $this->image2;
    }

    /**
     * @param mixed $image2
     */
    public function setImage2($image2)
    {
        $this->image2 = $image2;
    }

    /**
     * @return mixed
     */
    public function getImage3()
    {
        return $this->image3;
    }

    /**
     * @param mixed $image3
     */
    public function setImage3($image3)
    {
        $this->image3 = $image3;
    }

    /**
     * @return mixed
     */
    public function getImage4()
    {
        return $this->image4;
    }

    /**
     * @param mixed $image4
     */
    public function setImage4($image4)
    {
        $this->image4 = $image4;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }



    /**
     * @return mixed
     */
    public function getTITRE()
    {
        return $this->TITRE;
    }

    /**
     * @param mixed $TITRE
     */
    public function setTITRE($TITRE)
    {
        $this->TITRE = $TITRE;
    }

    /**
     * @return mixed
     */
    public function getNOMBREDECYLINDRES()
    {
        return $this->NOMBRE_DE_CYLINDRES;
    }

    /**
     * @param mixed $NOMBRE_DE_CYLINDRES
     */
    public function setNOMBREDECYLINDRES($NOMBRE_DE_CYLINDRES)
    {
        $this->NOMBRE_DE_CYLINDRES = $NOMBRE_DE_CYLINDRES;
    }

    /**
     * @return mixed
     */
    public function getENERGIE()
    {
        return $this->ENERGIE;
    }

    /**
     * @param mixed $ENERGIE
     */
    public function setENERGIE($ENERGIE)
    {
        $this->ENERGIE = $ENERGIE;
    }

    /**
     * @return mixed
     */
    public function getPUISSANCEFISCALE()
    {
        return $this->PUISSANCE_FISCALE;
    }

    /**
     * @param mixed $PUISSANCE_FISCALE
     */
    public function setPUISSANCEFISCALE($PUISSANCE_FISCALE)
    {
        $this->PUISSANCE_FISCALE = $PUISSANCE_FISCALE;
    }

    /**
     * @return mixed
     */
    public function getCYLINDREE()
    {
        return $this->CYLINDREE;
    }

    /**
     * @param mixed $CYLINDREE
     */
    public function setCYLINDREE($CYLINDREE)
    {
        $this->CYLINDREE = $CYLINDREE;
    }

    /**
     * @return mixed
     */
    public function getBOITE()
    {
        return $this->BOITE;
    }

    /**
     * @param mixed $BOITE
     */
    public function setBOITE($BOITE)
    {
        $this->BOITE = $BOITE;
    }

    /**
     * @return mixed
     */
    public function getDESCRIPITION()
    {
        return $this->DESCRIPITION;
    }

    /**
     * @param mixed $DESCRIPITION
     */
    public function setDESCRIPITION($DESCRIPITION)
    {
        $this->DESCRIPITION = $DESCRIPITION;
    }

    /**
     * @return mixed
     */
    public function getVALIDATION()
    {
        return $this->VALIDATION;
    }

    /**
     * @param mixed $VALIDATION
     */
    public function setVALIDATION($VALIDATION)
    {
        $this->VALIDATION = $VALIDATION;
    }

    /**
     * @return mixed
     */
    public function getPRIX()
    {
        return $this->PRIX;
    }

    /**
     * @param mixed $PRIX
     */
    public function setPRIX($PRIX)
    {
        $this->PRIX = $PRIX;
    }


    public function __construct()
    {
        // Par défaut, la date de l'annonce est la date d'aujourd'hui
        $this->date = new \Datetime();
    }


}

pidev/src/pidev/UserBundle/Resources/views/Admin/adminAnnonces.html.twig
{% extends ':admin:baseAdmin.html.twig' %}
{% block content %}

    <div class="content container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-title">Static Tables <small>Different variations</small></h2>
             <div style="float: left"> <button class="btn btn-sm btn-primary"><a href="{{ path('ex' )}}">exporter les annonces en excel</a> </button></div>

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="widget">
                    <div class="widget-header"> <i class="icon-table"></i>
                        <h3>Table</h3>
                    </div>
                    <div class="widget-content">
                        <div class="body">
                            <table class="table table-striped table-images">
                                <thead>
                                <tr>
                                    <th>image</th>
                                    <th>Id</th>
                                    <th>Id_User</th>
                                    <th>Titre</th>
                                    <th class="hidden-xs">Date</th>
                                    <th class="hidden-xs">Prix</th>
                                    <th class="hidden-xs">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for annonce in annonces %}
                                <tr>

                                    <td><img src="{{asset ('/images/' ~ annonce.image ~ '')}}"></td>
                                    <td> <a href="{{ path('annonces_show', { 'id': annonce.ID }) }}">{{ annonce.ID }}</a> </td>
                                    <td> {{ annonce.user.id }} </td>
                                    <td> {{ annonce.tITRE }} </td>
                                    <td class="hidden-xs"> {% if annonce.date %}{{ annonce.date|date('Y-m-d') }}{% endif %} </td>
                                    <td> {{ annonce.pRIX }} </td>
                                    <td class="hidden-xs"><button class="btn btn-sm btn-primary"><a href="{{ path('show_admin', { 'id': annonce.ID }) }}">show</a> </button>
                                    <td class="hidden-xs"><button class="btn btn-sm btn-warning"><a href="{{ path('annoce_delete', { 'id': annonce.ID }) }}}">delete</a> </button>
                                </tr>
{% endfor %}

                                </tbody>
                            </table>
                            {{ knp_pagination_render(annonces) }}


                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

{% endblock %}

pidev/src/pidev/UserBundle/Resources/views/Admin/adminShow.html.twig
{% extends ':admin:baseAdmin.html.twig' %}

{% block content %}
    <div class="wrapper">

    <div class="page-content">
        <div class="content container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-title">Annonce<small> Out of the box form</small></h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="widget">
                        <div class="widget-header"> <i class="icon-user"></i>
                            <h3>Annonce</h3>
                        </div>
                        <div class="widget-content">
                            <div class="body">
                                <form data-validate="parsley" method="post" novalidate class="form-horizontal label-left" id="user-form">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="text-align-center"> <img style="height: 112px;" alt="64x64" src="{{asset ('/images/' ~ annonce.image ~ '')}}" class="img-circle"> </div>
                                        </div>
                                        <div class="col-md-8">
                                            <h3 class="no-margin">Titre :   {{ annonce.tITRE }}</h3>
                                        </div>
                                    </div>
                                    <fieldset>
                                        <legend>Account Edit Form <small>Some explanation text</small></legend>
                                    </fieldset>
                                    <fieldset>


                                        <div class="control-group">
                                            <div class="col-md-3">
                                                <label for="first-name" class="control-label">Id <span class="required">:</span></label>
                                            </div>
                                            <div class="col-md-9">
                                                <div class="form-group" ; style="text-align: center">
                                                                {{ annonce.id }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <div class="col-md-3">
                                                <label for="first-name" class="control-label">Id_user <span class="required">:</span></label>
                                            </div>
                                            <div class="col-md-9">
                                                <div class="form-group" ; style="text-align: center">
                                                    {{ annonce.user.id }}
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <div class="col-md-3">
                                                    <label for="first-name" class="control-label">Date<span class="required">:</span></label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-group" ; style="text-align: center">
                                                        {% if annonce.date %}{{ annonce.date|date('Y-m-d') }}{% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <div class="col-md-3">
                                                    <label for="first-name" class="control-label">NOMBRE_DE_CYLINDRES <span class="required">:</span></label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-group" ; style="text-align: center">
                                                        {{ annonce.nOMBREDECYLINDRES }}
                                                    </div>
                                                </div>
                                                <div class="control-group">
                                                    <div class="col-md-3">
                                                        <label for="first-name" class="control-label">Region <span class="required">:</span></label>
                                                    </div>
                                                    <div class="col-md-9">
                                                        <div class="form-group" ; style="text-align: center">
                                                            {{ annonce.region }}
                                                        </div>
                                                    </div>
                                                <div class="control-group">
                                                    <div class="col-md-3">
                                                        <label for="first-name" class="control-label">ENERGIE <span class="required">:</span></label>
                                                    </div>
                                                    <div class="col-md-9">
                                                        <div class="form-group" ; style="text-align: center">
                                                            {{ annonce.eNERGIE }}
                                                        </div>
                                                    </div>
                                                    <div class="control-group">
                                                        <div class="col-md-3">
                                                            <label for="first-name" class="control-label">PUISSANCE_FASCIALE <span class="required">:</span></label>
                                                        </div>
                                                        <div class="col-md-9">
                                                            <div class="form-group" ; style="text-align: center">
                                                                {{ annonce.pUISSANCEFISCALE }}
                                                            </div>
                                                        </div>
                                                        <div class="control-group">
                                                            <div class="col-md-3">
                                                                <label for="first-name" class="control-label">CYLINDREE <span class="required">:</span></label>
                                                            </div>
                                                            <div class="col-md-9">
                                                                <div class="form-group" ; style="text-align: center">
                                                                    {{ annonce.cYLINDREE }}
                                                                </div>
                                                            </div>
                                                            <div class="control-group">
                                                                <div class="col-md-3">
                                                                    <label for="first-name" class="control-label">BOITE <span class="required">:</span></label>
                                                                </div>
                                                                <div class="col-md-9">
                                                                    <div class="form-group" ; style="text-align: center">
                                                                        {{ annonce.bOITE }}
                                                                    </div>
                                                                </div>
                                                                <div class="control-group">
                                                                    <div class="col-md-3">
                                                                        <label for="first-name" class="control-label">PRIX <span class="required">:</span></label>
                                                                    </div>
                                                                    <div class="col-md-9">
                                                                        <div class="form-group" ; style="text-align: center">
                                                                            {{ annonce.pRIX }}
                                                                        </div>
                                                                    </div>
                                                                    <div class="control-group">
                                                                        <div class="col-md-3">
                                                                            <label for="first-name" class="control-label">DESCRIPITION <span class="required">:</span></label>
                                                                        </div>
                                                                        <div class="col-md-9">
                                                                            <div class="form-group" ; style="text-align: center">
                                                                                {{ annonce.dESCRIPITION }}
                                                                            </div>
                                                                        </div>



                                        </div></div>

                                    </fieldset>
                                    <fieldset>
                                        <legend class="section">Contact Info</legend>
                                        <div class="control-group">
                                            <div class="col-md-3">
                                                <label for="first-name" class="control-label">Num_Tel <span class="required">:</span></label>
                                            </div>
                                            <div class="col-md-9">
                                                <div class="form-group" ; style="text-align: center">
                                                    {{ annonce.user.numTel }}
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <div class="col-md-3">
                                                    <label for="first-name" class="control-label">E-mail <span class="required">:</span></label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-group" ; style="text-align: center">
                                                        {{ annonce.user.email }}
                                                    </div>
                                                </div>

                                    </fieldset>
                                    <div class="form-actions">
                                        <button data-toggle="button" class="btn btn-sm btn-warning"><a href="{{ path('annonces_delete', { 'id': annonce.ID }) }}">Delete</a>  </button></td>
                                        <button class="btn btn-default" type="button"><a href="{{ path('annonces_index') }}">Back to the list</a></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

pidev/src/pidev/UserBundle/Resources/views/Admin/home.html.twig
{% extends ':admin:baseAdmin.html.twig' %}

pidev/src/pidev/UserBundle/Resources/views/Admin/listoffres.twig
{% extends ':admin:baseAdmin.html.twig' %}
{% block content %}

    <div class="content container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-title">Offres</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="widget">
                    <div class="widget-header"> <i class="icon-table"></i>
                        <h3>Liste des offres</h3>
                    </div>
                    <div class="widget-content">
                        <div class="body">
                            <table class="table table-striped table-images">
                                <thead>
                                <tr>
                                    <th>image</th>
                                    <th>ID</th>
                                    <th>Nom Offre</th>
                                    <th>Description</th>
                                    <th>Supprimer</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for offre in offres %}
                                    <tr>

                                        <td><img src="{{asset ('/pictures/' ~ offre.photo ~ '')}}"></td>
                                        <td> {{ offre.id }} </td>
                                        <td><a href="{{ path('offre_show',{'id': offre.id}) }}"> {{ offre.nomOffre }} </a> </td>
                                        <td> {{ offre.description }} </td>
                                        <td class="hidden-xs"><button class="btn btn-sm btn-warning"><a href="{{ path('delete_offre', { 'id': offre.id }) }}">Supprimer</a> </button></td>
                                    </tr>
                                {% endfor %}
                                <div align="center" style="float: left;margin-left: 35%">
                                    <div class="row">
                                        <div class="pagination">
                                            <div class="col-xs-12">

                                                {{ knp_pagination_render(offres) }}
                                            </div>

                                        </div>
                                    </div>

                                </div>


                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pidev/src/pidev/UserBundle/Resources/views/Admin/listusers.html.twig
{% extends ':admin:baseAdmin.html.twig' %}
{% block content %}

    <div class="content container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-title">Utilisateurs</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="widget">
                    <div class="widget-header"> <i class="icon-table"></i>
                        <h3>Liste de tout les utilisateurs</h3>
                    </div>
                    <div class="widget-content">
                        <div class="body">
                            <table class="table table-striped table-images">
                                <thead>
                                <tr>
                                    <th>image</th>
                                    <th>ID</th>
                                    <th>nom d'utilisateur</th>
                                    <th>numéro téléphone</th>
                                    <th>Supprimer</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for user in users %}
                                    <tr>

                                        <td><img src="{{asset ('/pictures/' ~ user.image ~ '')}}"></td>
                                        <td> {{ user.id }} </td>
                                        <td> {{ user.username }} </td>
                                        <td> {{ user.numTel }} </td>
                                        <td class="hidden-xs"><button class="btn btn-sm btn-warning"><a href="{{ path('delete_user', { 'id': user.id }) }}">Supprimer</a> </button></td>

                                    </tr>
                                {% endfor %}
                                <div align="center" style="float: left;margin-left: 35%">
                                    <div class="row">
                                        <div class="pagination">
                                            <div class="col-xs-12">

                                                {{ knp_pagination_render(users) }}
                                            </div>

                                        </div>
                                    </div>

                                </div>


                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pidev/src/pidev/UserBundle/Resources/views/Admin/validationAnnonces.html.twig
{% extends ':admin:baseAdmin.html.twig' %}
{% block content %}

        <div class="content container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-title">List Annonces Non Validé</h2>
                    <div style="float: left"> <button class="btn btn-sm btn-primary"><a href="{{ path('ex' )}}">exporter les annonces en excel</a> </button></div>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="widget">
                        <div class="widget-header"> <i class="icon-table"></i>
                            <h3>Table</h3>
                        </div>
                        <div class="widget-content">
                            <div class="body">
                                <table class="table table-striped table-images">
                                    <thead>
                                    <tr>
                                        <th>image</th>
                                        <th>Id</th>
                                        <th>Id_User</th>
                                        <th>Titre</th>
                                        <th class="hidden-xs">Date</th>
                                        <th class="hidden-xs">Prix</th>
                                        <th class="hidden-xs">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for annonce in annonces %}
                                        <tr>

                                            <td><img src="{{asset ('/images/' ~ annonce.image ~ '')}}"></td>
                                            <td> <a href="{{ path('annonces_show', { 'id': annonce.ID }) }}">{{ annonce.ID }}</a> </td>
                                            <td> {{ annonce.user.id}} </td>
                                            <td> {{ annonce.tITRE }} </td>
                                            <td class="hidden-xs"> {% if annonce.date %}{{ annonce.date|date('Y-m-d') }}{% endif %} </td>
                                            <td> {{ annonce.pRIX }} </td>
                                            <td class="hidden-xs"><button class="btn btn-sm btn-primary"><a href="{{ path('show_admin', { 'id': annonce.ID }) }}">show</a> </button>

                                            <td class="hidden-xs"><button class="btn btn-sm btn-warning"><a href="{{ path('delet_annonce', { 'id': annonce.ID }) }}}">delete</a> </button>
                                            <td class="hidden-xs"><button class="btn btn-sm btn-success"><a href="{{ path('valid', { 'id': annonce.ID }) }}}">validation</a> </button>

                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                                {{ knp_pagination_render(annonces) }}


                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}